<?php

namespace symfony\CinemaBundle\Repository;

/**
 * auteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class auteurRepository extends \Doctrine\ORM\EntityRepository
{
}
